CREATE DATABASE gigachad;
CREATE TABLE chats (
ChatID BIGINT NOT NULL,
Title VARCHAR(255) NOT NULL,
State BOOLEAN NOT NULL DEFAULT FALSE,
PRIMARY KEY(ChatID)
);

INSERT INTO chats 
VALUE(100000, 'Default', FALSE);
